# Generated by Django 5.0.4 on 2024-05-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0003_department_leaveandattendance_performance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('imgUrl', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.RemoveField(
            model_name='leaveandattendance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birthplace',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='surname',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='LeaveAndAttendance',
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
