# Generated by Django 5.0.4 on 2024-05-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0006_delete_recipe_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='employee',
            name='birthplace',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
