# Generated by Django 5.0.4 on 2024-05-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0007_employee_birthdate_employee_birthplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(default='12-02-2002'),
        ),
    ]
