# Generated by Django 5.0.4 on 2024-05-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0008_alter_employee_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(default=None),
        ),
    ]
