# Generated by Django 5.0.4 on 2024-05-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0009_alter_employee_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
