# Generated by Django 5.0.4 on 2024-05-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0010_remove_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birthdate',
        ),
    ]
