# Generated by Django 5.0.4 on 2024-05-17 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0013_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='datejoined',
            field=models.DateField(default=datetime.datetime(2024, 5, 17, 21, 44, 42, 410323)),
        ),
    ]
