# Generated by Django 5.0.4 on 2024-05-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0014_employee_datejoined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='datejoined',
            field=models.DateField(default=None),
        ),
    ]
